services:
  postgres:
    image: postgres:15
    container_name: easset-postgres
    environment:
      POSTGRES_USER: easset
      POSTGRES_PASSWORD: easset
      POSTGRES_DB: easset_development
    ports:
      - "5441:5432"
    volumes:
      - easset_postgres_data:/var/lib/postgresql/data

volumes:
  easset_postgres_data: